###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: rpg-backend-mailhog
      ports:
        - "1701:8025"

    mysql:
      image: mysql:5.7
      container_name: rpg-backend-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=app
        - MYSQL_DATABASE=app
        - MYSQL_USER=app
        - MYSQL_PASSWORD=app
      ports:
        - "1702:3306"

    webserver:
      image: nginx:alpine
      container_name: rpg-backend-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1700:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: rpg-backend-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

